server:
  port: 8760

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: peer2
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/, http://peer3:8759/eureka/