server:
  port: 8002

spring:
  application:
    name: service-config-client

# springboot2.0后要加这玩意，而不是那个management.security.enabled=false，这是1.5的过时方法了
management:
  endpoints:
    web:
      exposure:
        include: refresh