server:
  port: 18764

spring:
  application:
    name: service-ribbon

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000